#!/usr/bin/env bash

cd "$(dirname "${0}")"

# base
source ./base
source ./rust

# neovim config
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

# h ledger
sudo dnf -y install hledger

# gnome extras
sudo dnf -y install gnome-tweaks 
sudo dnf -y install gnome-extensions-app 
sudo dnf -y install gnome-shell-extension-pop-shell

# set user config
$HOME/Source/github.com/jeffwindsor/dotfiles/fedora

