#!/usr/bin/env bash
cd "$(dirname "${0}")"

menu(){
  while :
  do
    clear
    echo -ne "

███████╗██╗██╗    ██╗   ██╗███████╗██████╗ ██████╗ ██╗     ██╗   ██╗███████╗
██╔════╝██║██║    ██║   ██║██╔════╝██╔══██╗██╔══██╗██║     ██║   ██║██╔════╝
███████╗██║██║    ██║   ██║█████╗  ██████╔╝██████╔╝██║     ██║   ██║█████╗  
╚════██║██║██║    ╚██╗ ██╔╝██╔══╝  ██╔══██╗██╔══██╗██║     ██║   ██║██╔══╝  
███████║██║███████╗╚████╔╝ ███████╗██║  ██║██████╔╝███████╗╚██████╔╝███████╗
╚══════╝╚═╝╚══════╝ ╚═══╝  ╚══════╝╚═╝  ╚═╝╚═════╝ ╚══════╝ ╚═════╝ ╚══════╝

u) Update (Reboot)
t) Create Daily Drive Toolbox
f) First time setup (Reboot)

Select Step:  "
    read -r step
    case $step in
      u) dnf_update
         rpm_ostree_update
         systemctl reboot
         ;;
      s) ssh_keygen;;
      c) configure_gnome;;
      i) install_user_software;;
      t) create_toolbox daily-driver;;
      f) 
         create_toolbox daily-driver
         rpm_ostree_update
         rpm_ostree_setup
         rpm_ostree_overlays
         systemctl reboot
         ;;
      *)
        echo "Not a valid option"
        exit 1
        ;;
    esac
  done
}

rpm_ostree_update(){
  sudo rpm-ostree upgrade
}

dnf_update(){
  sudo dnf -y update
}

rpm_ostree_setup(){
  # set rpm ostree updates to automatic
  sudo cp ./rpm-ostreed.conf /etc
  rpm-ostree reload
  systemctl enable rpm-ostreed-automatic.timer --now
}

rpm_ostree_overlays(){
  rpm-ostree install pop-shell alacritty
}

create_toolbox(){
  toolbox create && toolbox run -c $1 ./toolbox/$1
}

menu
