#!/usr/bin/env bash

#   
#    █████╗ ██████╗  ██████╗██╗  ██╗              ██╗  ██╗███╗   ███╗ ██████╗ ███╗   ██╗ █████╗ ██████╗ 
#   ██╔══██╗██╔══██╗██╔════╝██║  ██║              ╚██╗██╔╝████╗ ████║██╔═══██╗████╗  ██║██╔══██╗██╔══██╗
#   ███████║██████╔╝██║     ███████║    █████╗     ╚███╔╝ ██╔████╔██║██║   ██║██╔██╗ ██║███████║██║  ██║
#   ██╔══██║██╔══██╗██║     ██╔══██║    ╚════╝     ██╔██╗ ██║╚██╔╝██║██║   ██║██║╚██╗██║██╔══██║██║  ██║
#   ██║  ██║██║  ██║╚██████╗██║  ██║              ██╔╝ ██╗██║ ╚═╝ ██║╚██████╔╝██║ ╚████║██║  ██║██████╔╝
#   ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝              ╚═╝  ╚═╝╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═════╝ 
#                                                                                                       

header(){ echo "==> " "$@"; }

install() {
	if pacman -Qi $1 &> /dev/null; then
  		header "["$1 "] is already installed"
	else
    	header "installing package ["$1"]"
    	sudo pacman -S --noconfirm --needed $1 
    fi
}

install-aur() {
	if paru -Qi $1 &> /dev/null; then
  		header "["$1 "] is already installed"
	else
    	header "installing ["$1"]" 
        paru -S --noconfirm "$1" 
    fi
}

header "System"
# Bluetooth
install bluez
install bluez-libs
install bluez-utils
# Laptop Power
install tlp
install-aur auto-cpufreq 
sudo systemctl enable auto-cpufreq
# Printing
install cups
# compositor
install picom
# xorg
install xorg-server
install xorg-xkill
install xorg-xmessage
install xorg-xprop
install xorg-xrdb
install xorg-xset
install xorg-xsetroot
install lxappearance
isntall lxsession

header "Xmonad"
install xmonad
install xmonad-contrib
install xmobar

# extras
install slock

