#!/usr/bin/env bash

header(){
    echo "==> " $@
}

install() {
	if pacman -Qi $1 &> /dev/null; then
  		header "["$1 "] is already installed"
	else
    	header "installing package ["$1"]"
    	sudo pacman -S --noconfirm --needed $1 
    fi
}

# MacbookPro Retina 15 Wifi: broadcom 14E4:43A0
#   https://unix.stackexchange.com/questions/175810/how-to-install-broadcom-bcm4360-on-debian-on-macbook-pro
install broadcom-sta-dkms
sudo modprobe -r b44 b43 b43legacy ssb brcmsmac
sudo modprobe wl
