#!/usr/bin/env bash

#   
#    █████╗ ██████╗  ██████╗██╗  ██╗
#   ██╔══██╗██╔══██╗██╔════╝██║  ██║
#   ███████║██████╔╝██║     ███████║
#   ██╔══██║██╔══██╗██║     ██╔══██║
#   ██║  ██║██║  ██║╚██████╗██║  ██║
#   ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝
#                                   

####################################################################################
# PRE STEPS
# validate disk is clear, and remove the current partitions
#   fdisk -l
#   fdisk /dev/sda1
# connect to internet
#   iwctl --passphrase $passphrase station wlan0 connect $SSID
#
# run archinstaller
####################################################################################

install(){ sudo pacman -S --noconfirm --needed "$@"; }
aur{ paru -S --noconfirm "$@"; }

ask(){
	echo "1 : Upgrade"
	echo "2 : Install Packages and GNOME Config"
	echo -n "> "
	read selection
	case $selection in

		1 )
			sudo pacman -Syu
            install_aur_helper
			;;

		2 )
			install_packages
            source ./shared/sshkeys
            source ./shared/gitclones
            source ./shared/gnome
			;;

		*) echo "Invalid input"
		    ;;
	esac
}

install_aur_helper(){
    install git
    git clone https://aur.archlinux.org/paru.git
    cd paru
    makepkg -si --noconfirm
    cd ..
    rm -rf paru
}

install_packages(){
    # bluetooth
    install bluez bluez-libs bluez-utils
    sudo systemctl enable bloothooth.service
    #frame laptop 1 device is bluetooth
    rfkill unblock 1

    # laptop power
    install tlp
    install-aur auto-cpufreq 
    sudo systemctl enable auto-cpufreq

    # z shell
    install zsh zsh-autosuggestions zsh-completions zsh-history-substring-search zsh-syntax-highlighting
    install starship
    chsh -s "$(which zsh)"          #Set ZSH as DEFAULT"
    
    # neovim
    install vim
    aur vim-plug
    nvim --headless +PlugInstall +qall

    # apps 
    install bat exa fd fzf ripgrep stow tldr
    install shellcheck
    install firefox
    install keychain
    aur nerd-fonts-complete

    #manual steps"
    xdg-open https://mega.nz/sync/ &
    xdg-open https://lastpass.com/ &

    install gnome-tweaks gnome-extra
    aur gnome-shell-extension-pop-shell-git 
}

ask
