#!/usr/bin/env bash

#   
#    █████╗ ██████╗  ██████╗██╗  ██╗               ██████╗ ███╗   ██╗ ██████╗ ███╗   ███╗███████╗
#   ██╔══██╗██╔══██╗██╔════╝██║  ██║              ██╔════╝ ████╗  ██║██╔═══██╗████╗ ████║██╔════╝
#   ███████║██████╔╝██║     ███████║    █████╗    ██║  ███╗██╔██╗ ██║██║   ██║██╔████╔██║█████╗  
#   ██╔══██║██╔══██╗██║     ██╔══██║    ╚════╝    ██║   ██║██║╚██╗██║██║   ██║██║╚██╔╝██║██╔══╝  
#   ██║  ██║██║  ██║╚██████╗██║  ██║              ╚██████╔╝██║ ╚████║╚██████╔╝██║ ╚═╝ ██║███████╗
#   ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝               ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝
#                                                                                                

header(){
    echo "==> " $@
}

install() {
	if pacman -Qi $1 &> /dev/null; then
  		header "["$1 "] is already installed"
	else
    	header "installing package ["$1"]"
    	sudo pacman -S --noconfirm --needed $1 
    fi
}

install-aur() {
	if paru -Qi $1 &> /dev/null; then
  		header "["$1 "] is already installed"
	else
    	header "installing package ["$1"]" 
        paru -S --noconfirm "$1" 
    fi
}

header "System"
# Bluetooth
install bluez
install bluez-libs
install bluez-utils
# Laptop Power
install tlp
install-aur auto-cpufreq 
sudo systemctl enable auto-cpufreq
# Printing
install cups
# compositor
install picom

header "Gnome"
install gnome
install gnome-tweaks
install gnome-extra

# tiling window extension
install-aur gnome-shell-extension-pop-shell-git 
# allows selecting of devices from taskbar tray
install-aur gnome-shell-extension-sound-output-device-chooser
# allows you to block sleep and screen saver 
install-aur gnome-shell-extension-caffeine-git

