#!/usr/bin/env bash

cd "$(dirname "${0}")"
#====================================================================================# 
# user space installs
#====================================================================================# 
# clis
sudo dnf -y install bat exa fd-find fzf gitui ripgrep rmlint starship stow

#cargo install grex
#cargo install mdcat
cargo install tealdeer
cargo install topgrade

# neovim
sudo dnf -y install neovim
sudo dnf -y install gcc "gcc-c++" glibc-all-langpacks

# astrovim (neovim config)
git clone --depth 1 git@github.com:AstroNvim/AstroNvim.git $HOME/.config/nvim
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

# helix
sudo dnf copr enable varlad/helix -y
sudo dnf -y install helix

# lazy git
sudo dnf copr enable atim/lazygit -y
sudo dnf -y install lazygit

# h ledger
sudo dnf -y install hledger

#====================================================================================# 
# gnome extras
sudo dnf -y install gnome-tweaks gnome-extensions-app 

#====================================================================================# 
# fish
sudo dnf -y install fish
sudo usermod -s $(which fish) $USERNAME

#plugins
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
fisher install PatrickF1/fzf.fish
fisher install jethrokuan/z
fisher install laughedelic/pisces
fisher install laughedelic/fish_logo
fisher install gazorby/fish-exa

#====================================================================================# 
# set user config
$HOME/Source/github.com/jeffwindsor/dotfiles/fedora

#====================================================================================# 
# git clones
#====================================================================================# 
# directories
mkdir -p $HOME/Source
mkdir -p $HOME/Source/gitlab.gnome.org/
mkdir -p $HOME/Source/gitlab.com/
mkdir -p $HOME/Source/github.com/

# repos
# git clone http://gitlab.gnome.org/jeffwindsor/gnome-shell-extensions.git $HOME/Source/gitlab.gnome.org/jeffwindsor/gnome-shell-extensions
git clone git@github.com:jeffwindsor/dotfiles.git $HOME/Source/github.com/jeffwindsor/dotfiles
git clone git@github.com:jeffwindsor/hledger-data.git $HOME/Source/github.com/jeffwindsor/hledger-data
git clone git@github.com:jeffwindsor/installs.git $HOME/Source/github.com/jeffwindsor/installs
git clone git@github.com:jeffwindsor/startpage.git $HOME/Source/github.com/jeffwindsor/startpage

#====================================================================================# 
# gnome settings
#====================================================================================# 
# pop shell highlight color
dconf write "/org/gnome/shell/extensions/pop-shell/hint-color-rgba" "'rgb(115,206,244)'"

# load gnome terminal profiles
dconf load /org/gnome/terminal/legacy/profiles:/ < $HOME/Source/github.com/jeffwindsor/installs/shared/gnome-terminal-profiles.dconf

# interface preferences
dconf write "/org/gnome/desktop/interface/clock-format" "'12h'"
dconf write "/org/gnome/desktop/interface/clock-show-weekday" "true"
dconf write "/org/gnome/desktop/interface/gtk-theme" "'Adwaita-dark'"
dconf write "/org/gnome/desktop/interface/text-scaling-factor" "1.25"
dconf write "/org/gnome/desktop/peripherals/touchpad/click-method" "'fingers'"
dconf write "/org/gnome/desktop/peripherals/touchpad/natural-scroll" "true"
dconf write "/org/gnome/desktop/peripherals/touchpad/speed" "0.4"
dconf write "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled" "true"
dconf write "/org/gnome/desktop/wm/preferences/button-layout" "'close:appmenu'"
dconf write "/org/gnome/desktop/wm/preferences/num-workspaces" "10"
dconf write "/org/gnome/mutter/dynamic-workspaces" "false"
dconf write "/org/gtk/settings/file-chooser/clock-format" "'12h'"
dconf write "/org/gnome/desktop/datetime/automatic-timezone" "true"
dconf write "/org/gnome/desktop/interface/locate-pointer" "true"
dconf write "/org/gnome/desktop/calendar/show-weekdate" "true"
dconf write "/org/gnome/mutter/workspaces-only-on-primary" "true"
# keyboard bindings : unset
dconf write "/org/gnome/desktop/wm/keybindings/begin-move" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/begin-resize" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/close" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/cycle-group" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/cycle-group-backward" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/cycle-windows" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/cycle-windows-backward" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-last" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/switch-input-source" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/switch-input-source-backward" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-last" "@as []"
dconf write "/org/gnome/shell/keybindings/focus-active-notification" "@as []"
dconf write "/org/gnome/mutter/keybindings/toggle-tiled-left" "@as []"
dconf write "/org/gnome/mutter/keybindings/toggle-tiled-right" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/area-screenshot-clip" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/logout" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/magnifier" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/screencast" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/screenreader" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/screenshot-clip" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/window-screenshot-clip" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/activate-launcher" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/pop-monitor-down" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/pop-monitor-left" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/pop-monitor-right" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/pop-monitor-up" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/pop-workspace-down" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/pop-workspace-up" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/toggle-floating" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/toggle-stacking" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/toggle-stacking-global" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/toggle-tiling" "@as []"
# keyboard bindings : set
dconf write "/org/gnome/desktop/wm/keybindings/close" "['<Super>q']"
dconf write "/org/gnome/desktop/wm/keybindings/minimize" "['<Super>w']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-1" "['<Primary><Super>1']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-10" "['<Primary><Super>0']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-2" "['<Primary><Super>2']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-3" "['<Primary><Super>3']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-4" "['<Primary><Super>4']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-5" "['<Primary><Super>5']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-6" "['<Primary><Super>6']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-7" "['<Primary><Super>7']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-8" "['<Primary><Super>8']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-9" "['<Primary><Super>9']"
dconf write "/org/gnome/desktop/wm/keybindings/panel-run-dialog" "['<Primary>space']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1" "['<Super>1']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-10" "['<Super>0']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2" "['<Super>2']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3" "['<Super>3']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4" "['<Super>4']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-5" "['<Super>5']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-6" "['<Super>6']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-7" "['<Super>7']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-8" "['<Super>8']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-9" "['<Super>9']"
dconf write "/org/gnome/desktop/wm/keybindings/toggle-fullscreen" "['<Primary><Super>m']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/area-screenshot" "['<Primary><Super>BackSpace']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/control-center" "['<Super>comma']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/next" "['AudioForward']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/previous" "['AudioRewind']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/window-screenshot" "['<Super>BackSpace']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/www" "['<Super>b']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/home" "['<Super>f']"
dconf write "/org/gnome/shell/keybindings/toggle-message-tray" "['<Super>n']"

# keyboard bindings : custom
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings" "[\
    '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', \
    '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', \
    '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', \
    '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', \
    '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/']"

dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding" "'<Primary><Super>S'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command" "'systemctl suspend'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name" "'Suspend'"

dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding" "'<Primary><Super>L'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command" "'gnome-session-quit --logout --no-prompt'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name" "'Logout'"

dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding" "'<Primary><Super>R'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command" "'shutdown -r now'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name" "'Reboot'"

dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/binding" "'<Primary><Super>P'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/command" "'shutdown -h now'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/name" "'Power-Off'"

dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/binding" "'<Super>t'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/command" "'gnome-terminal'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/name" "'Terminal'"
#====================================================================================# 
# app images
#====================================================================================# 
# https://github.com/aferrero2707/gimp-appimage/releases
# https://github.com/KRTirtho/spotube/releases
#====================================================================================# 
# flatpak
#====================================================================================# 
# ADD FLATHUB REPO
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# FLATPAKS
flatpaks=(
    "com.github.tchx84.Flatseal"
    "com.mattjakeman.ExtensionManager"
    "com.spotify.Client"
)
for fp in ${flatpaks[@]}; do
    flatpak install -y $fp
done

# UNDER REVIEW
#   "com.valvesoftware.Steam"
#   "com.jetbrains.IntelliJ-IDEA-Community"
#   "md.obsidian.Obsidian"
#   "org.gnome.Geary"
#   "com.vscodium.codium"

# vscode helper: https://github.com/owtaylor/toolbox-vscode
#====================================================================================# 
# git extensions
#====================================================================================# 
# https://extensions.gnome.org/extension/3193/blur-my-shell/ &
# https://extensions.gnome.org/extension/3843/just-perfection/ &
# https://extensions.gnome.org/extension/600/launch-new-instance/ &

# https://extensions.gnome.org/extension/615/appindicator-support/ &
# https://extensions.gnome.org/extension/3396/color-picker/
# https://extensions.gnome.org/extension/4135/espresso/ &
# https://extensions.gnome.org/extension/3956/gnome-fuzzy-app-search/ &
# https://extensions.gnome.org/extension/4472/spotify-tray/ &
# https://extensions.gnome.org/extension/21/workspace-indicator/ &

# https://extensions.gnome.org/extension/1401/bluetooth-quick-connect/ &
# https://extensions.gnome.org/extension/906/sound-output-device-chooser/ &
#====================================================================================# 
