#!/usr/bin/env bash

#   
#   ███████╗███████╗██████╗  ██████╗ ██████╗  █████╗    
#   ██╔════╝██╔════╝██╔══██╗██╔═══██╗██╔══██╗██╔══██╗  
#   █████╗  █████╗  ██║  ██║██║   ██║██████╔╝███████║ 
#   ██╔══╝  ██╔══╝  ██║  ██║██║   ██║██╔══██╗██╔══██║   
#   ██║     ███████╗██████╔╝╚██████╔╝██║  ██║██║  ██║ 
#   ╚═╝     ╚══════╝╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
#                                                                                                                 

cd "$(dirname "${0}")"

# package manager update
sudo dnf -y upgrade

# extra repositories
sudo dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf -y install https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# packages
sudo dnf -y install tlp
sudo dnf -y install alacritty 
sudo dnf -y install bat exa fd-find fzf ripgrep stow tldr 
sudo dnf -y install zsh zsh-autosuggestions zsh-syntax-highlighting starship
sudo dnf -y install neovim

# gnome
sudo dnf -y install gnome-tweaks
sudo dnf -y install gnome-shell-extension-appindicator
sudo dnf -y install gnome-shell-extension-caffeine
sudo dnf -y install gnome-shell-extension-just-perfection
sudo dnf -y install gnome-shell-extension-launch-new-instance
sudo dnf -y install gnome-shell-extension-pop-shell 
sudo dnf -y install gnome-shell-extension-sound-output-device-chooser
#  remove unwanted
sudo dnf -y remove gnome-shell-extension-apps-menu

#echo "==> NVIM PLUGINS"
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim --headless +PlugInstall +qall

# make zsh my default
sudo dnf -y install util-linux-user
chsh -s "$(which zsh)"

# manual installs
xdg-open https://extensions.gnome.org/extension/3193/blur-my-shell/ &
xdg-open https://mega.nz/sync &
