#!/usr/bin/env bash

#   
#   ███████╗███████╗██████╗  ██████╗ ██████╗  █████╗                ██████╗ ███╗   ██╗ ██████╗ ███╗   ███╗███████╗
#   ██╔════╝██╔════╝██╔══██╗██╔═══██╗██╔══██╗██╔══██╗              ██╔════╝ ████╗  ██║██╔═══██╗████╗ ████║██╔════╝
#   █████╗  █████╗  ██║  ██║██║   ██║██████╔╝███████║    █████╗    ██║  ███╗██╔██╗ ██║██║   ██║██╔████╔██║█████╗  
#   ██╔══╝  ██╔══╝  ██║  ██║██║   ██║██╔══██╗██╔══██║    ╚════╝    ██║   ██║██║╚██╗██║██║   ██║██║╚██╔╝██║██╔══╝  
#   ██║     ███████╗██████╔╝╚██████╔╝██║  ██║██║  ██║              ╚██████╔╝██║ ╚████║╚██████╔╝██║ ╚═╝ ██║███████╗
#   ╚═╝     ╚══════╝╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝               ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝
#                                                                                                                 

cd "$(dirname "${0}")"

# package manager update
sudo dnf -y upgrade

# packages
sudo dnf -y install tlp
sudo dnf -y install alacritty 
sudo dnf -y install bat exa fd-find fzf ripgrep stow tldr 
sudo dnf -y install zsh zsh-autosuggestions zsh-syntax-highlighting starship
sudo dnf -y install neovim

sudo dnf -y install gnome-tweaks
sudo dnf -y install gnome-shell-extension-pop-shell 
sudo dnf -y install gnome-shell-extension-sound-output-device-chooser
sudo dnf -y install gnome-shell-extension-caffeine
sudo dnf -y install gnome-shell-extension-launch-new-instance

# make zsh my default
sudo dnf -y install util-linux-user
chsh -s "$(which zsh)"

# manual
xdg-open https://mega.nz/sync &
