#!/usr/bin/env bash

cd "$(dirname "${0}")"
#====================================================================================# 
# app images
#====================================================================================# 
# https://github.com/aferrero2707/gimp-appimage/releases
# https://github.com/KRTirtho/spotube/releases
#====================================================================================# 
# flatpak
#====================================================================================# 
# ADD FLATHUB REPO
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# FLATPAKS
flatpaks=(
    "com.github.tchx84.Flatseal"
    "com.mattjakeman.ExtensionManager"
    "com.spotify.Client"
)
for fp in ${flatpaks[@]}; do
    flatpak install -y $fp
done

# UNDER REVIEW
#   "com.valvesoftware.Steam"
#   "com.jetbrains.IntelliJ-IDEA-Community"
#   "md.obsidian.Obsidian"
#   "org.gnome.Geary"
#   "com.vscodium.codium"

# vscode helper: https://github.com/owtaylor/toolbox-vscode
#====================================================================================# 
# git extensions
#====================================================================================# 
# https://extensions.gnome.org/extension/3193/blur-my-shell/ &
# https://extensions.gnome.org/extension/3843/just-perfection/ &
# https://extensions.gnome.org/extension/600/launch-new-instance/ &

# https://extensions.gnome.org/extension/615/appindicator-support/ &
# https://extensions.gnome.org/extension/3396/color-picker/
# https://extensions.gnome.org/extension/4135/espresso/ &
# https://extensions.gnome.org/extension/3956/gnome-fuzzy-app-search/ &
# https://extensions.gnome.org/extension/4472/spotify-tray/ &
# https://extensions.gnome.org/extension/21/workspace-indicator/ &

# https://extensions.gnome.org/extension/1401/bluetooth-quick-connect/ &
# https://extensions.gnome.org/extension/906/sound-output-device-chooser/ &
#====================================================================================# 
