#!/usr/bin/env bash
cd "$(dirname "${0}")"

menu(){
  while :
  do
    clear
    echo -ne "

███████╗███████╗██████╗  ██████╗ ██████╗  █████╗ 
██╔════╝██╔════╝██╔══██╗██╔═══██╗██╔══██╗██╔══██╗
█████╗  █████╗  ██║  ██║██║   ██║██████╔╝███████║
██╔══╝  ██╔══╝  ██║  ██║██║   ██║██╔══██╗██╔══██║
██║     ███████╗██████╔╝╚██████╔╝██║  ██║██║  ██║
╚═╝     ╚══════╝╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝

o) Setup
u) Update

Select Step:  "
    read -r step
    case $step in
      u) 
        dnf_update
        ;;
      s)
        dnf_setup
        dnf_update
        dnf_installs
        ;;
      *)
        echo "Not a valid option"
        exit 1
        ;;
    esac
  done
}

dnf_setup(){
  # update dnf config
  echo "max_parallel_downloads=10" | sudo tee -a /etc/dnf/dnf.conf
  echo "defaultyes=True" | sudo tee -a /etc/dnf/dnf.conf
  echo "fastestmirror=True" | sudo tee -a /etc/dnf/dnf.conf

  # add rpm fusion repositories
  sudo dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
  sudo dnf -y install https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
}

dnf_update(){
  sudo dnf -y upgrade
}

dnf_installs(){
  # clis
  sudo dnf -y install alacritty 
  sudo dnf -y install bat 
  sudo dnf -y install exa
  sudo dnf -y install fd-find
  sudo dnf -y install fortune-mod
  sudo dnf -y install fzf
  sudo dnf -y install hledger
  sudo dnf -y install ripgrep
  #sudo dnf -y install rmlint
  #sudo dnf -y install starship
  sudo dnf -y install stow
  sudo dnf -y install tealdeer

  # tiling
  sudo dnf -y install pop-shell

  # neovim
  sudo dnf -y install neovim
  sudo dnf -y install gcc "gcc-c++" glibc-all-langpacks
  sudo dnf -y install openssl openssl-devel

  # fish
  sudo dnf -y install fish

  #====================================================================================# 
  # manual tasks
  #====================================================================================# 
  echo "* Login into Lastpass"
  echo "* Goto Github and add public ssh key"
}

menu
