#!/usr/bin/env bash

#   
#   ███████╗███████╗██████╗  ██████╗ ██████╗  █████╗                ██████╗ ███╗   ██╗ ██████╗ ███╗   ███╗███████╗
#   ██╔════╝██╔════╝██╔══██╗██╔═══██╗██╔══██╗██╔══██╗              ██╔════╝ ████╗  ██║██╔═══██╗████╗ ████║██╔════╝
#   █████╗  █████╗  ██║  ██║██║   ██║██████╔╝███████║    █████╗    ██║  ███╗██╔██╗ ██║██║   ██║██╔████╔██║█████╗  
#   ██╔══╝  ██╔══╝  ██║  ██║██║   ██║██╔══██╗██╔══██║    ╚════╝    ██║   ██║██║╚██╗██║██║   ██║██║╚██╔╝██║██╔══╝  
#   ██║     ███████╗██████╔╝╚██████╔╝██║  ██║██║  ██║              ╚██████╔╝██║ ╚████║╚██████╔╝██║ ╚═╝ ██║███████╗
#   ╚═╝     ╚══════╝╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝               ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝
#                                                                                                                 

cd "$(dirname "${0}")"

alias install='sudo dnf -y install'

# package manager update
sudo dnf -y upgrade

# non-free repos, do not need to do this after fedora 35
install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
install https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# laptop power
install tlp

# terminal
install alacritty 
install bat exa fd-find fzf ripgrep stow tldr 
install zsh zsh-autosuggestions zsh-syntax-highlighting starship

install neovim

# need chsh to set default shell
install util-linux-user

# for extra settings
install gnome-tweaks

install gnome-shell-extension-pop-shell 
install gnome-shell-extension-sound-output-device-chooser
install gnome-shell-extension-caffeine-git
install gnome-shell-extension-launch-new-instance

# make zsh my default
chsh -s "$(which zsh)"

# manual
xdg-open https://mega.nz/sync
