#!/usr/bin/env bash

#   
#    ██████╗ ██╗████████╗     ██████╗ ██████╗ ██╗      ██████╗ ███╗   ██╗███████╗███████╗
#   ██╔════╝ ██║╚══██╔══╝    ██╔════╝██╔═══██╗██║     ██╔═══██╗████╗  ██║██╔════╝██╔════╝
#   ██║  ███╗██║   ██║       ██║     ██║   ██║██║     ██║   ██║██╔██╗ ██║█████╗  ███████╗
#   ██║   ██║██║   ██║       ██║     ██║   ██║██║     ██║   ██║██║╚██╗██║██╔══╝  ╚════██║
#   ╚██████╔╝██║   ██║       ╚██████╗╚██████╔╝███████╗╚██████╔╝██║ ╚████║███████╗███████║
#    ╚═════╝ ╚═╝   ╚═╝        ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚══════╝
#                                                                                        

mkdir -p ${HOME}/src/github.com/
mkdir -p ${HOME}/src/gitlab.com/

git clone git@github.com:jeffwindsor/dotfiles $HOME/.dotfiles
git clone git@github.com:jeffwindsor/installs $HOME/.installs
git clone git@github.com:jeffwindsor/learn $HOME/src/github.com/jeffwindsor/learn
git clone git@github.com:jeffwindsor/startpage $HOME/src/github.com/jeffwindsor/startpage
