#!/usr/bin/env bash

mkdir -p ${HOME}/src/github.com/
mkdir -p ${HOME}/src/gitlab.com/

cd 
git clone https://github.com/jeffwindsor/dotfiles $HOME/.dotfiles
git clone https://github.com/jeffwindsor/setups $HOME/.setups

cd $HOME/src/github.com/
git clone https://github.com/jeffwindsor/learn
git clone https://github.com/jeffwindsor/startpage

cd 


