#!/usr/bin/env bash

mkdir -p ${HOME}/src/github.com/
mkdir -p ${HOME}/src/gitlab.com/

if [[ -d $HOME/.dotfiles ]]; then
    cd $HOME/.dotfiles
    git remote set-url origin git@github.com:jeffwindsor/dotfiles
else
    git clone git@github.com:jeffwindsor/dotfiles $HOME/.dotfiles
fi

if [[ -d $HOME/.dotfiles ]]; then
    cd $HOME/.dotfiles
    git remote set-url origin git@github.com:jeffwindsor/installs
else
    git clone git@github.com:jeffwindsor/installs $HOME/.installs
fi


git clone git@github.com:jeffwindsor/learn $HOME/src/github.com/jeffwindsor/learn
git clone git@github.com:jeffwindsor/startpage $HOME/src/github.com/jeffwindsor/startpage

