#!/usr/bin/env bash

#   
#    ██████╗ ███╗   ██╗ ██████╗ ███╗   ███╗███████╗
#   ██╔════╝ ████╗  ██║██╔═══██╗████╗ ████║██╔════╝
#   ██║  ███╗██╔██╗ ██║██║   ██║██╔████╔██║█████╗  
#   ██║   ██║██║╚██╗██║██║   ██║██║╚██╔╝██║██╔══╝  
#   ╚██████╔╝██║ ╚████║╚██████╔╝██║ ╚═╝ ██║███████╗
#    ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝
#                                                  

set -e
cd "$(dirname "${0}")"

function echo-color(){ 
    printf "\033[0;32m==> $1 \033[0m \n" 
}

echo-color "Extensions"
gnome-extensions enable pop-shell@system76.com
gnome-extensions enable sound-output-device-chooser@kgshank.net
gnome-extensions enable caffeine@patapon.info

echo-color "Desktop Look"
#dconf write "/org/gnome/desktop/interface/gtk-theme" "Adwaita-dark"
dconf write "/org/gnome/desktop/interface/text-scaling-factor" "1.12"
dconf write "/org/gnome/desktop/interface/clock-show-weekday" "true"
#dconf write "/org/gnome/desktop/wm/preferences/button-layout" "close:appmenu"
dconf write "/org/gnome/desktop/peripherals/touchpad/speed" "0.4"


echo-color "Keybindings: Applications"
dconf write '/org/gnome/settings-daemon/plugins/media-keys/terminal' "['<Super>Return']"
dconf write '/org/gnome/settings-daemon/plugins/media-keys/www' "['<Super><Alt>Return']"
dconf write '/org/gnome/settings-daemon/plugins/media-keys/home' "['<Super><Alt><Primary>Return']"
dconf write '/org/gnome/settings-daemon/plugins/media-keys/control-center' "['<Super>comma']"
dconf write '/org/gnome/settings-daemon/plugins/media-keys/email' '@as []'

echo-color "Keybindings: System"
dconf write "/org/gnome/shell/desktop/wm/keybindings/close" "['<Super>q']"

# gnome run command dialog
dconf write "/org/gnome/desktop/wm/keybindings/panel-run-dialog" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/panel-run-dialog" "['<Super><Alt>space']"

# like: alfred

# like: mission control
dconf write "/org/gnome/desktop/wm/keybindings/panel-main-menu" "['<Super>Up']"

echo-color "Keybindings: Workspaces"
dconf write "/org/gnome/mutter/dynamic-workspaces" "false"
dconf write "/org/gnome/desktop/wm/preferences/num-workspaces" "9"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1" "['<Super>1']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2" "['<Super>2']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3" "['<Super>3']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4" "['<Super>4']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-5" "['<Super>5']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-6" "['<Super>6']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-7" "['<Super>7']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-8" "['<Super>8']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-9" "['<Super>9']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-last" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-1" "['<Super><Alt>1']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-2" "['<Super><Alt>2']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-3" "['<Super><Alt>3']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-4" "['<Super><Alt>4']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-4" "['<Super><Alt>4']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-5" "['<Super><Alt>5']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-6" "['<Super><Alt>6']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-7" "['<Super><Alt>7']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-8" "['<Super><Alt>8']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-9" "['<Super><Alt>9']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-up" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-down" "@as []"

echo-color "Keybindings: Monitors"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-monitor-left" "['<Super><Alt><Shift>Left', '<Super><Alt><Shift>h']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-monitor-right" "['<Super><Alt><Shift>Right', '<Super><Alt><Shift>l']"

echo-color "Keybindings: Application Switching"
dconf write "/org/gnome/desktop/wm/keybindings/switch-applications-backward" "['<Shift><Super>Tab']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-applications" "['<Super>Tab']"
dconf write "/org/gnome/desktop/wm/keybindings/cycle-applications-backward" "['<Shift><Alt><Super>Tab']"
dconf write "/org/gnome/desktop/wm/keybindings/cycle-applications" "['<Alt><Super>Tab']"


MEDIA_KEYS='/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings' 
addCustom(){
    dconf write "$MEDIA_KEYS/custom$1/binding" "$2"
    dconf write "$MEDIA_KEYS/custom$1/command" "$3"
    dconf write "$MEDIA_KEYS/custom$1/name" "$4"
}

# create custom key entries
dconf write "$MEDIA_KEYS" "['$MEDIA_KEYS/custom0/','$MEDIA_KEYS/custom1/']"

echo-color "Keybindings: Launch Terminal"
addCustom "0" "'<Super>Return'" "'alacritty'" "'Terminal'"
echo-color "Keybindings: Launch Logout Tool"
addCustom "1" "'<Super>x'" "'arcolinux-logout'" "'Logout Tool'"

echo-color "Keybindings: Tiling (PopShell)"
dconf write '/org/gnome/shell/extensions/pop-shell/activate-launcher' "@as ['<Super>space']"

dconf write '/org/gnome/shell/extensions/pop-shell/tile-enter' "@as []"
dconf write '/org/gnome/shell/extensions/pop-shell/tile-enter' "@as ['<Super>m']"

dconf write '/org/gnome/shell/extensions/pop-shell/focus-left' "@as ['<Super>h']"
dconf write '/org/gnome/shell/extensions/pop-shell/focus-up' "@as ['<Super>k']"
dconf write '/org/gnome/shell/extensions/pop-shell/focus-down' "@as ['<Super>j']"
dconf write '/org/gnome/shell/extensions/pop-shell/focus-right' "@as ['<Super>l']"

dconf write '/org/gnome/shell/extensions/pop-shell/tile-move-left' "@as ['<Super><Alt>h']"
dconf write '/org/gnome/shell/extensions/pop-shell/tile-move-up' "@as ['<Super><Alt>k']"
dconf write '/org/gnome/shell/extensions/pop-shell/tile-move-down' "@as ['<Super><Alt>j']"
dconf write '/org/gnome/shell/extensions/pop-shell/tile-move-right' "@as ['<Super><Alt>l']"

dconf write '/org/gnome/shell/extensions/pop-shell/tile-swap-left' "@as ['<Super><Primary><Alt>h']"
dconf write '/org/gnome/shell/extensions/pop-shell/tile-swap-up' "@as ['<Super><Primary><Alt>k']"
dconf write '/org/gnome/shell/extensions/pop-shell/tile-swap-down' "@as ['<Super><Primary><Alt>j']"
dconf write '/org/gnome/shell/extensions/pop-shell/tile-swap-right' "@as ['<Super><Primary><Alt>l']"

dconf write '/org/gnome/shell/extensions/pop-shell/tile-resize-left' "@as ['<Super><Shift>h']"
dconf write '/org/gnome/shell/extensions/pop-shell/tile-resize-up' "@as ['<Super><Shift>k']"
dconf write '/org/gnome/shell/extensions/pop-shell/tile-resize-down' "@as ['<Super><Shift>j']"
dconf write '/org/gnome/shell/extensions/pop-shell/tile-resize-right' "@as ['<Super><Shift>l']"

# remove these keys
dconf write '/org/gnome/shell/extensions/pop-shell/pop-monitor-left' "@as []"
dconf write '/org/gnome/shell/extensions/pop-shell/pop-monitor-right' "@as []"
dconf write '/org/gnome/shell/extensions/pop-shell/pop-monitor-down' "@as []"
dconf write '/org/gnome/shell/extensions/pop-shell/pop-monitor-up' "@as []"

dconf write '/org/gnome/shell/extensions/pop-shell/pop-workspace-left' "@as []"
dconf write '/org/gnome/shell/extensions/pop-shell/pop-workspace-right' "@as []"
dconf write '/org/gnome/shell/extensions/pop-shell/pop-workspace-down' "@as []"
dconf write '/org/gnome/shell/extensions/pop-shell/pop-workspace-up' "@as []"
