#!/usr/bin/env bash

#   
#    ██████╗ ███╗   ██╗ ██████╗ ███╗   ███╗███████╗
#   ██╔════╝ ████╗  ██║██╔═══██╗████╗ ████║██╔════╝
#   ██║  ███╗██╔██╗ ██║██║   ██║██╔████╔██║█████╗  
#   ██║   ██║██║╚██╗██║██║   ██║██║╚██╔╝██║██╔══╝  
#   ╚██████╔╝██║ ╚████║╚██████╔╝██║ ╚═╝ ██║███████╗
#    ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝
#                                                  

set -e
cd "$(dirname "${0}")"

# interface preferences
dconf write "/org/gnome/desktop/interface/clock-format" "'12h'"
dconf write "/org/gnome/desktop/interface/clock-show-weekday" "true"
dconf write "/org/gnome/desktop/interface/gtk-theme" "'Adwaita-dark'"
dconf write "/org/gnome/desktop/interface/text-scaling-factor" "1.25"
dconf write "/org/gnome/desktop/peripherals/touchpad/click-method" "'fingers'"
dconf write "/org/gnome/desktop/peripherals/touchpad/natural-scroll" "true"
dconf write "/org/gnome/desktop/peripherals/touchpad/speed" "0.4"
dconf write "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled" "true"
dconf write "/org/gnome/desktop/wm/preferences/button-layout" "'close:appmenu'"
dconf write "/org/gnome/desktop/wm/preferences/num-workspaces" "10"
dconf write "/org/gnome/mutter/dynamic-workspaces" "false"
dconf write "/org/gtk/settings/file-chooser/clock-format" "'12h'"

# keyboard bindings : unset
dconf write "/org/gnome/desktop/wm/keybindings/begin-move" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/begin-resize" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/close" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/cycle-group" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/cycle-group-backward" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/cycle-windows" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/cycle-windows-backward" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-last" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/switch-input-source" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/switch-input-source-backward" "@as []"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-last" "@as []"
dconf write "/org/gnome/mutter/keybindings/toggle-tiled-left" "@as []"
dconf write "/org/gnome/mutter/keybindings/toggle-tiled-right" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/area-screenshot-clip" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/logout" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/magnifier" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/screencast" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/screenreader" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/screenshot-clip" "@as []"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/window-screenshot-clip" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/activate-launcher" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/pop-monitor-down" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/pop-monitor-left" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/pop-monitor-right" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/pop-monitor-up" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/pop-workspace-down" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/pop-workspace-up" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/toggle-floating" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/toggle-stacking" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/toggle-stacking-global" "@as []"
dconf write "/org/gnome/shell/extensions/pop-shell/toggle-tiling" "@as []"
dconf write "/org/gnome/shell/keybindings/focus-active-notification" "@as []"

# keyboard bindings : set
dconf write "/org/gnome/desktop/wm/keybindings/close" "['<Super>q']"
dconf write "/org/gnome/desktop/wm/keybindings/minimize" "['<Super>w']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-1" "['<Primary><Super>1']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-10" "['<Primary><Super>0']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-2" "['<Primary><Super>2']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-3" "['<Primary><Super>3']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-4" "['<Primary><Super>4']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-5" "['<Primary><Super>5']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-6" "['<Primary><Super>6']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-7" "['<Primary><Super>7']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-8" "['<Primary><Super>8']"
dconf write "/org/gnome/desktop/wm/keybindings/move-to-workspace-9" "['<Primary><Super>9']"
dconf write "/org/gnome/desktop/wm/keybindings/panel-run-dialog" "['<Primary>space']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1" "['<Super>1']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-10" "['<Super>0']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2" "['<Super>2']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3" "['<Super>3']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4" "['<Super>4']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-5" "['<Super>5']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-6" "['<Super>6']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-7" "['<Super>7']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-8" "['<Super>8']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-9" "['<Super>9']"
dconf write "/org/gnome/desktop/wm/keybindings/toggle-fullscreen" "['<Primary><Super>m']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/area-screenshot" "['<Primary><Super>BackSpace']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/control-center" "['<Super>comma']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/next" "['AudioForward']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/previous" "['AudioRewind']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/window-screenshot" "['<Super>BackSpace']"
dconf write "/org/gnome/shell/keybindings/toggle-message-tray" "['<Super>n']"

# keyboard bindings : custom
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings" "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/']"

dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding" "'<Primary>Delete'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command" "'shutdown -r now'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name" "'Reboot'"

dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding" "'<Primary><Super>Delete'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command" "'shutdown -h now'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name" "'Power-Off'"

dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/binding" "'<Primary><Super>Escape'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/command" "'gnome-session-quit --logout --no-prompt'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/name" "'Logout'"

dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/binding" "'<Super>t'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/command" "'gnome-terminal'"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/name" "'Terminal'"

