#!/usr/bin/env bash

cd "$(dirname "${0}")"
#====================================================================================# 
# 
#   /$$$$$$  /$$ /$$                               /$$       /$$                          
#  /$$__  $$|__/| $$                              | $$      | $$                          
# | $$  \__/ /$$| $$ /$$    /$$ /$$$$$$   /$$$$$$ | $$$$$$$ | $$ /$$   /$$  /$$$$$$       
# |  $$$$$$ | $$| $$|  $$  /$$//$$__  $$ /$$__  $$| $$__  $$| $$| $$  | $$ /$$__  $$      
#  \____  $$| $$| $$ \  $$/$$/| $$$$$$$$| $$  \__/| $$  \ $$| $$| $$  | $$| $$$$$$$$      
#  /$$  \ $$| $$| $$  \  $$$/ | $$_____/| $$      | $$  | $$| $$| $$  | $$| $$_____/      
# |  $$$$$$/| $$| $$   \  $/  |  $$$$$$$| $$      | $$$$$$$/| $$|  $$$$$$/|  $$$$$$$      
#  \______/ |__/|__/    \_/    \_______/|__/      |_______/ |__/ \______/  \_______/      
#                                                                                         
#====================================================================================# 
# ssh keygen
#====================================================================================# 
if [[ ! -f $HOME/.ssh/github.com ]]; then
    ssh-keygen -t ed25519 -f $HOME/.ssh/github.com -C "jeff.windsor@gmail.com"
    xdg-open https://github.com/settings/keys/ &
fi

if [[ ! -f $HOME/.ssh/gitlab.gnome.org ]]; then
    ssh-keygen -t ed25519 -f $HOME/.ssh/gitlab.gnome.org -C "jeff.windsor+gnome@gmail.com"
    xdg-open https://gitlab.gnome.org/-/profile/keys/ &
fi
#====================================================================================# 
# rmp-ostree
#====================================================================================# 
sudo rpm-ostree upgrade

# automatic rpm ostree updates
sudo cp ./rpm-ostreed.conf /etc
rpm-ostree reload
systemctl enable rpm-ostreed-automatic.timer --now

# overlays
rpm-ostree install pop-shell

# reboot for changes
systemctl reboot
#====================================================================================# 
