#!/usr/bin/env bash

#_____/\\\\\\\\\\\__________/\\\\\\________________________________________________/\\\_________/\\\\\\_________________________________        
# ___/\\\/////////\\\_______\////\\\_______________________________________________\/\\\________\////\\\_________________________________       
#  __\//\\\______\///___/\\\____\/\\\_______________________________________________\/\\\___________\/\\\_________________________________      
#   ___\////\\\_________\///_____\/\\\_____/\\\____/\\\_____/\\\\\\\\___/\\/\\\\\\\__\/\\\___________\/\\\_____/\\\____/\\\_____/\\\\\\\\__     
#    ______\////\\\_______/\\\____\/\\\____\//\\\__/\\\____/\\\/////\\\_\/\\\/////\\\_\/\\\\\\\\\_____\/\\\____\/\\\___\/\\\___/\\\/////\\\_    
#     _________\////\\\___\/\\\____\/\\\_____\//\\\/\\\____/\\\\\\\\\\\__\/\\\___\///__\/\\\////\\\____\/\\\____\/\\\___\/\\\__/\\\\\\\\\\\__   
#      __/\\\______\//\\\__\/\\\____\/\\\______\//\\\\\____\//\\///////___\/\\\_________\/\\\__\/\\\____\/\\\____\/\\\___\/\\\_\//\\///////___  
#       _\///\\\\\\\\\\\/___\/\\\__/\\\\\\\\\____\//\\\______\//\\\\\\\\\\_\/\\\_________\/\\\\\\\\\___/\\\\\\\\\_\//\\\\\\\\\___\//\\\\\\\\\\_ 
#        ___\///////////_____\///__\/////////______\///________\//////////__\///__________\/////////___\/////////___\/////////_____\//////////__
#


cd "$(dirname "${0}")"

ask(){
	echo "1 : Upgrade"
	echo "2 : Install Packages and GNOME Config"
	echo -n "> "
	read selection
	case $selection in

		1 )
			update
            restart
			;;

		2 )
			create_layer
            restart
			;;

        3 ) 
            user_space
            gnome
            ;;

		*) echo "Invalid input"
		    ;;
	esac
}

update(){
	echo "==> Updating"
    rpm-ostree upgrade
}

create_layer(){
	echo "==> Creating Pesonalization Layer"
    rpm-ostree install bat exa fd-find fzf ripgrep stow tldr \
        util-linux-user webp-pixbuf-loader \
        zsh zsh-autosuggestions zsh-syntax-highlighting \
        starship neovim \
        gnome-tweaks gnome-shell-extension-pop-shell
}

user_space(){
    # vim plug (for neovim)
    sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
	nvim --headless +PlugInstall +qall

    # applications
    sudo flatpak install -y flathub com.spotify.Client
    sudo flatpak install -y flathub com.vscodium.codium
    sudo flatpak install -y flathub com.valvesoftware.Steam

	# gen ssh key
	if [[ ! -f $HOME/.ssh/id_ed25519 ]]; then
	    ssh-keygen -t ed25519 -C "jeff.windsor@gmail.com"
	    xdg-open https://github.com/settings/keys/
	fi

	# git repositories
	mkdir -p ${HOME}/src/github.com/
	mkdir -p ${HOME}/src/gitlab.com/
	git clone git@github.com:jeffwindsor/dotfiles $HOME/.dotfiles
	git clone git@github.com:jeffwindsor/installs $HOME/.installs
	git clone git@github.com:jeffwindsor/startpage $HOME/src/github.com/jeffwindsor/startpage

	# set zsh as default shell
	chsh -s "$(which zsh)"

	# add appropriate folders to local from MEGA 
	#  if not added to one of the standard folder, add it to gnome search (such as books from mega) : Settings > Search > Search Locations > Other
	xdg-open https://mega.nz/sync/ &

    # terminal color schemes
    xdg-open https://mayccoll.github.io/Gogh/ &
    # favorites: 12 13 06 59 72 136 141 195 201
    
    # update gnome preferences
    source ./gnome
}

ask
