#!/usr/bin/env bash

cd "$(dirname "${0}")"
#====================================================================================# 
# fedora dnf 
#====================================================================================# 
# update dnf config
echo "max_parallel_downloads=10" | sudo tee -a /etc/dnf/dnf.conf
echo "defaultyes=True" | sudo tee -a /etc/dnf/dnf.conf
echo "fastestmirror=True" | sudo tee -a /etc/dnf/dnf.conf

# add rpm fusion repositories
sudo dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf -y install https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# upgrade packages
sudo dnf -y upgrade
#====================================================================================# 
# user space installs
#====================================================================================# 
# clis
sudo dnf -y install bat exa fd-find fzf gitui ripgrep rmlint starship stow

# neovim
sudo dnf -y install neovim
sudo dnf -y install gcc "gcc-c++" glibc-all-langpacks

# astrovim (neovim config)
git clone --depth 1 git@github.com:AstroNvim/AstroNvim.git $HOME/.config/nvim
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

# helix
#sudo dnf copr enable varlad/helix -y
#sudo dnf -y install helix

# lazy git
sudo dnf copr enable atim/lazygit -y
sudo dnf -y install lazygit

# h ledger
sudo dnf -y install hledger

#====================================================================================# 
# gnome extras
sudo dnf -y install gnome-tweaks gnome-extensions-app 

#====================================================================================# 
# fish
sudo dnf -y install fish
sudo usermod -s $(which fish) $USERNAME

#plugins
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
fisher install PatrickF1/fzf.fish
fisher install jethrokuan/z
fisher install laughedelic/pisces
fisher install laughedelic/fish_logo
fisher install gazorby/fish-exa

#====================================================================================# 
# set user config
$HOME/Source/github.com/jeffwindsor/dotfiles/fedora

#====================================================================================# 
# rust
#====================================================================================# 

# rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# cargo update
sudo dnf install openssl openssl-dev && cargo install cargo-update

# updater
cargo install topgrade

cargo install bacon
cargo install grex
cargo install mdcat
cargo install tealdeer

#====================================================================================# 
