#!/usr/bin/env bash
cd "$(dirname "${0}")"

#
#     /$$$$$$  /$$ /$$                               /$$       /$$                    
#    /$$__  $$|__/| $$                              | $$      | $$                    
#   | $$  \__/ /$$| $$ /$$    /$$ /$$$$$$   /$$$$$$ | $$$$$$$ | $$ /$$   /$$  /$$$$$$ 
#   |  $$$$$$ | $$| $$|  $$  /$$//$$__  $$ /$$__  $$| $$__  $$| $$| $$  | $$ /$$__  $$
#    \____  $$| $$| $$ \  $$/$$/| $$$$$$$$| $$  \__/| $$  \ $$| $$| $$  | $$| $$$$$$$$
#    /$$  \ $$| $$| $$  \  $$$/ | $$_____/| $$      | $$  | $$| $$| $$  | $$| $$_____/
#   |  $$$$$$/| $$| $$   \  $/  |  $$$$$$$| $$      | $$$$$$$/| $$|  $$$$$$/|  $$$$$$$
#    \______/ |__/|__/    \_/    \_______/|__/      |_______/ |__/ \______/  \_______/
#                                                                                     

ask(){
  echo "1 : OsTree Upgrade"
  echo "2 : OsTree PopShell Layer"
  echo "3 : User Space and Toolbox"
  echo -n "> "
  read selection
  case $selection in

    1 )
      sudo rpm-ostree upgrade
      systemctl restart
      ;;

    2 )
      sudo rpm-ostree install gnome-shell-extension-pop-shell
      systemctl restart
      ;;

    3)
      source ./shared/sshkeys
      source ./shared/gitclones
      source ./shared/gnome
      source ./shared/flathub
      
      source ./toolboxes/base
      source ./shared/gnome-extensions
      ;;

    *) 
      echo "Invalid input"
      ;;
  esac
}

ask
