#!/usr/bin/env bash
cd "$(dirname "${0}")"
# 
#   /$$$$$$  /$$ /$$                               /$$       /$$                          
#  /$$__  $$|__/| $$                              | $$      | $$                          
# | $$  \__/ /$$| $$ /$$    /$$ /$$$$$$   /$$$$$$ | $$$$$$$ | $$ /$$   /$$  /$$$$$$       
# |  $$$$$$ | $$| $$|  $$  /$$//$$__  $$ /$$__  $$| $$__  $$| $$| $$  | $$ /$$__  $$      
#  \____  $$| $$| $$ \  $$/$$/| $$$$$$$$| $$  \__/| $$  \ $$| $$| $$  | $$| $$$$$$$$      
#  /$$  \ $$| $$| $$  \  $$$/ | $$_____/| $$      | $$  | $$| $$| $$  | $$| $$_____/      
# |  $$$$$$/| $$| $$   \  $/  |  $$$$$$$| $$      | $$$$$$$/| $$|  $$$$$$/|  $$$$$$$      
#  \______/ |__/|__/    \_/    \_______/|__/      |_______/ |__/ \______/  \_______/      
#                                                                                         
#=====================================================================================                                                                                                                 
# ssh keygen
#=====================================================================================                                                                                                                 
if [[ ! -f $HOME/.ssh/github.com ]]; then
    ssh-keygen -t ed25519 -f $HOME/.ssh/github.com -C "jeff.windsor@gmail.com"
    xdg-open https://github.com/settings/keys/ &
fi

if [[ ! -f $HOME/.ssh/gitlab.gnome.org ]]; then
    ssh-keygen -t ed25519 -f $HOME/.ssh/gitlab.gnome.org -C "jeff.windsor+gnome@gmail.com"
    xdg-open https://gitlab.gnome.org/-/profile/keys/ &
fi
#=====================================================================================                                                                                                                 
# rmp-ostree
#=====================================================================================                                                                                                                 

sudo rpm-ostree upgrade
sudo rpm-ostree install gnome-shell-extension-pop-shell

#=====================================================
echo
echo "Post Setup Tasks"
echo "1) Open Firefox and login for sync"
echo "2) Login into Lastpass"
echo "3) Goto Github and add public ssh key"
echo
read -p "Press ANY Key to reboot (once rebooted run user space script)"
systemctl reboot
'
