#!/bin/bash

if [[ ! -f $HOME/.ssh/id_ed25519 ]]; then
    header "Generate SSH key and add to Github"
    ssh-keygen -t ed25519 -C "jeff.windsor@gmail.com"
    eval $(ssh-agent)
    ssh-add ~/.ssh/id_ed25519
    xdg-open https://github.com/settings/keys/
fi

# add new key to github
xdg-open https://github.com/settings/keys
