#!/usr/bin/env bash

# clis
sudo dnf -y install bat exa fd-find fzf ripgrep starship stow tldr

# neovim
sudo dnf -y install neovim
git clone git@github.com:AstroNvim/AstroNvim.git $HOME/.config/nvim
sudo dnf -y install gcc "gcc-c++"

# install gui
sudo dnf -y install gnome-tweaks gnome-extensions-app 

# zsh as default shell
sudo dnf -y install zsh zsh-autosuggestions zsh-syntax-highlighting
sudo usermod -s $(which zsh) $USERNAME

