#!/usr/bin/env bash
cd "$(dirname "${0}")"

# add flathub repo
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

sudo flatpak install -y flathub com.spotify.Client
sudo flatpak install -y flathub com.valvesoftware.Steam
sudo flatpak install -y flathub nz.mega.MEGAsync
sudo flatpak install -y flathub com.github.Eloston.UngoogledChromium
sudo flatpak install -y flathub com.jetbrains.IntelliJ-IDEA-Community
sudo flatpak install -y com.github.geigi.cozy
