#!/usr/bin/env bash
cd "$(dirname "${0}")"

# add flathub repo
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

flatpaks=(
    "com.belmoussaoui.Obfuscate"
    "com.github.Eloston.UngoogledChromium"
    "com.github.geigi.cozy"
    "com.github.tchx84.Flatseal"
    "com.jetbrains.IntelliJ-IDEA-Community"
    "com.spotify.Client"
    "com.valvesoftware.Steam"
    "com.vscodium.codium"
    "de.haeckerfelix.Shortwave"
    "nz.mega.MEGAsync"
    "org.gabmus.gfeed"
)

for fp in ${flatpaks[@]}; do
    flatpak install -y flathub $fp
done
