#!/usr/bin/env bash

cd "$(dirname "${0}")"

loc='../'

# == Silverblue ==============================================================
sb='silverblue'
sbu="$sb-user-space"
sbut="$sbu-toolbox"

cat \
  header \
  fedora/silverblue-logo \
  sshkeys \
  fedora/rpm-ostree \
  tasks \
  > $loc$sb

chmod +x $loc$sb

# == Silverblue User Space ====================================================
cat header \
  gitclones \
  appimages \
  flatpaks \
  gnome \
  fedora/silverblue-gnome-custom \
  > $loc$sbu 

cat << EOF >> $loc$sbu

# base toolbox
toolbox create
toolbox run ./$sbut
EOF

chmod +x $loc$sbu

# == Silverblue Toolbox =======================================================
target='../silverblue-user-space-toolbox'

cat \
  fedora/dnf-config \
  fedora/user-space-installs \
  fedora/dev-rust \
  fedora/dev-go \
  > $loc$sbut

chmod +x $loc$sbut


# == Fedora ===================================================================
f='fedora'
fu="$f-user-space"

cat \
  header \
  fedora/logo \
  sshkeys \
  fedora/dnf-config \
  tasks \
  > $loc$f

chmod +x $loc$f

# == Fedora User Space ========================================================
cat \
  header \
  fedora/user-space-installs \
  gitclones \
  gnome \
  appimages \
  flatpaks \
  gnome-extensions \
  > $loc$fu 

chmod +x $loc$fu

