#!/usr/bin/env bash
cd "$(dirname "${0}")"
# 
# __/\\\\\\\\\\\__________________________________________________________/\\\\\\_____/\\\\\\_________________        
#  _\/////\\\///__________________________________________________________\////\\\____\////\\\_________________       
#   _____\/\\\____________________________________/\\\________________________\/\\\_______\/\\\_________________      
#    _____\/\\\______/\\/\\\\\\____/\\\\\\\\\\__/\\\\\\\\\\\__/\\\\\\\\\_______\/\\\_______\/\\\_____/\\\\\\\\\\_     
#     _____\/\\\_____\/\\\////\\\__\/\\\//////__\////\\\////__\////////\\\______\/\\\_______\/\\\____\/\\\//////__    
#      _____\/\\\_____\/\\\__\//\\\_\/\\\\\\\\\\____\/\\\________/\\\\\\\\\\_____\/\\\_______\/\\\____\/\\\\\\\\\\_   
#       _____\/\\\_____\/\\\___\/\\\_\////////\\\____\/\\\_/\\___/\\\/////\\\_____\/\\\_______\/\\\____\////////\\\_  
#        __/\\\\\\\\\\\_\/\\\___\/\\\__/\\\\\\\\\\____\//\\\\\___\//\\\\\\\\/\\__/\\\\\\\\\__/\\\\\\\\\__/\\\\\\\\\\_ 
#         _\///////////__\///____\///__\//////////______\/////_____\////////\//__\/////////__\/////////__\//////////__
# 
 
#=====================================================
# Silverblue
target='../silverblue'

cat \
  header \
  fedora/silverblue-logo \
  sshkeys \
  fedora/rpm-ostree \
  > $target

cat << EOF >> $target
#=====================================================
echo
echo "Post Setup Tasks"
echo "1) Open Firefox and login for sync"
echo "2) Login into Lastpass"
echo "3) Goto Github and add public ssh key"
echo
read -p "Press ANY Key to reboot (once rebooted run user space script)"
systemctl reboot
'
EOF

chmod +x $target

# Silverblue User Space
target='../silverblue-user-space'

cat \
  gitclones \
  appimages \
  flatpaks \
  gnome-extensions \
  gnome \
  > $target 

cat << EOF >> $target
#=====================================================
# base toolbox
#=====================================================
toolbox create
toolbox run sh -exec '
EOF

cat \
  fedora/dnf-config \
  fedora/user-space-installs \
  fedora/dev-rust \
  fedora/dev-go \
  >> $target

cat << EOF >> $target
'

systemctl reboot
EOF

chmod +x $target


#=====================================================
# Fedora
target='../fedora'

cat \
  header \
  fedora/logo \
  sshkeys \
  fedora/dnf-config \
  fedora/user-space-installs \
  gitclones \
  gnome \
  > $target

cat << EOF >> $target
systemctl reboot
EOF

chmod +x $target

# User Space 
target='../fedora-user-space'

cat \
  appimages \
  flatpaks \
  gnome-extensions \
  > $target 

chmod +x $target

