#!/usr/bin/env bash
cd "$(dirname "${0}")"
# 
# __/\\\\\\\\\\\__________________________________________________________/\\\\\\_____/\\\\\\_________________        
#  _\/////\\\///__________________________________________________________\////\\\____\////\\\_________________       
#   _____\/\\\____________________________________/\\\________________________\/\\\_______\/\\\_________________      
#    _____\/\\\______/\\/\\\\\\____/\\\\\\\\\\__/\\\\\\\\\\\__/\\\\\\\\\_______\/\\\_______\/\\\_____/\\\\\\\\\\_     
#     _____\/\\\_____\/\\\////\\\__\/\\\//////__\////\\\////__\////////\\\______\/\\\_______\/\\\____\/\\\//////__    
#      _____\/\\\_____\/\\\__\//\\\_\/\\\\\\\\\\____\/\\\________/\\\\\\\\\\_____\/\\\_______\/\\\____\/\\\\\\\\\\_   
#       _____\/\\\_____\/\\\___\/\\\_\////////\\\____\/\\\_/\\___/\\\/////\\\_____\/\\\_______\/\\\____\////////\\\_  
#        __/\\\\\\\\\\\_\/\\\___\/\\\__/\\\\\\\\\\____\//\\\\\___\//\\\\\\\\/\\__/\\\\\\\\\__/\\\\\\\\\__/\\\\\\\\\\_ 
#         _\///////////__\///____\///__\//////////______\/////_____\////////\//__\/////////__\/////////__\//////////__
# 
loc='../'

#=====================================================
# Silverblue
sb='silverblue'
sbu="$sb-user-space"
sbut="$sbu-toolbox"

cat \
  header \
  fedora/silverblue-logo \
  sshkeys \
  fedora/rpm-ostree \
  > $loc$sb

cat << EOF >> $loc$sb
#=====================================================
echo
echo "Post Setup Tasks"
echo "1) Open Firefox and login for sync"
echo "2) Login into Lastpass"
echo "3) Goto Github and add public ssh key"
echo
read -p "Press ANY Key to reboot (once rebooted run user space script)"
systemctl reboot
'
EOF

chmod +x $loc$sb

#=====================================================
# Silverblue User Space
cat header \
  gitclones \
  appimages \
  flatpaks \
  gnome \
  fedora/silverblue-gnome-custom \
  > $loc$sbu 

cat << EOF >> $loc$sbu

# base toolbox
toolbox create
toolbox run ./$sbut
EOF

chmod +x $loc$sbu

#=====================================================
# Silverblue Toolbox
target='../silverblue-user-space-toolbox'

cat \
  fedora/dnf-config \
  fedora/user-space-installs \
  fedora/dev-rust \
  fedora/dev-go \
  > $loc$sbut

chmod +x $loc$sbut


#=====================================================
# Fedora
f='fedora'
fu="$f-user-space"

cat \
  header \
  fedora/logo \
  sshkeys \
  fedora/dnf-config \
  fedora/user-space-installs \
  gitclones \
  gnome \
  > $loc$f

cat << EOF >> $target
systemctl reboot
EOF

chmod +x $loc$f

#=====================================================
# Fedora User Space 
cat \
  header \
  appimages \
  flatpaks \
  gnome-extensions \
  > $loc$fu 

chmod +x $loc$fu

