#!/usr/bin/env bash

cd "$(dirname "${0}")"
#====================================================================================# 
# fedora dnf 
#====================================================================================# 
# update dnf config
echo "max_parallel_downloads=10" | sudo tee -a /etc/dnf/dnf.conf
echo "defaultyes=True" | sudo tee -a /etc/dnf/dnf.conf
echo "fastestmirror=True" | sudo tee -a /etc/dnf/dnf.conf

# add rpm fusion repositories
sudo dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf -y install https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# upgrade packages
sudo dnf -y upgrade

# clis
sudo dnf -y install bat 
sudo dnf -y install exa
sudo dnf -y install fd-find
sudo dnf -y install fortune-mod
sudo dnf -y install fzf
sudo dnf -y install ripgrep
#sudo dnf -y install rmlint
#sudo dnf -y install starship
sudo dnf -y install stow
sudo dnf -y install tealdeer

# neovim
sudo dnf -y install neovim
sudo dnf -y install gcc "gcc-c++" glibc-all-langpacks

# helix
#sudo dnf copr enable varlad/helix -y
#sudo dnf -y install helix

# lazy git
sudo dnf copr enable atim/lazygit -y
sudo dnf -y install lazygit

# fish
sudo dnf -y install fish

# fish-plugins
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
fisher install PatrickF1/fzf.fish
#fisher install jethrokuan/z
#fisher install laughedelic/pisces
#fisher install laughedelic/fish_logo
fisher install gazorby/fish-exa

#====================================================================================# 
# manual tasks
#====================================================================================# 
echo "* Login into Lastpass"
echo "* Goto Github and add public ssh key"

