#!/usr/bin/env bash

  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  cargo install cargo-update
  sudo dnf -y install cmake && cargo install starship
  cargo install topgrade
